/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ortx4j;

// import ai.onnxruntime.OrtSession.Result;
// import ai.onnxruntime.OrtSession.SessionOptions;
// import ai.onnxruntime.OrtSession.SessionOptions.ExecutionMode;
// import ai.onnxruntime.OrtSession.SessionOptions.OptLevel.*;

import ai.onnxruntime.extensions.*;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        long handle = Utils.getNativeExtensionOperatorRegister();
        System.out.println(new App().getGreeting() + String.valueOf(handle));
    }
}
