parameters:
- name: CibwEnv
  displayName: 'Extra env variable set to CIBW_ENVIRONMENT, in form of "A=1 B=2 C=3"'
  type: string
  default: ''

- name: artifact_feed
  displayName: 'Artifact feed'
  type: string
  default: 'ORT-Nightly'

stages:
- stage: Windows_Build
  dependsOn: []
  jobs:
  - job: main
    timeoutInMinutes: 120
    pool:
      name: onnxruntime-Win-CPU-2022
      os: windows

    variables:
      CIBW_BUILD: cp3{10,11,12,13}-*amd64
      CIBW_ARCHS: AMD64
      CIBW_ENVIRONMENT: "${{ parameters.CibwEnv }}"
      CIBW_BUILD_VERBOSITY: 1
    templateContext:
      outputs:
      - output: pipelineArtifact
        path: '$(REPOROOT)\out'
        artifact: drop_Windows_Build_main

    steps:
    - script: |
        @echo off
        set vswherepath="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
        for /f "usebackq delims=" %%i in (`%vswherepath% -latest -property installationPath`) do (
          set vslatest="%%i"
          if exist "%%i\Common7\Tools\vsdevcmd.bat" (
            set vsdevcmd="%%i\Common7\Tools\vsdevcmd.bat"
          )
          if exist "%%i\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" (
            set vscmake="%%i\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
          )
          if exist "%%i\MSBuild\Current\Bin\amd64\msbuild.exe" (
            set vsmsbuild="%%i\MSBuild\Current\Bin\amd64\msbuild.exe"
          )
        )

        @echo vslatest %vslatest%
        @echo vsdevcmd %vsdevcmd%
        @echo vscmake %vscmake%
        @echo vsmsbuild %vsmsbuild%

        @echo ##vso[task.setvariable variable=vslatest]%vslatest%
        @echo ##vso[task.setvariable variable=vsdevcmd]%vsdevcmd%
        @echo ##vso[task.setvariable variable=vscmake]%vscmake%
        @echo ##vso[task.setvariable variable=vsmsbuild]%vsmsbuild%
      displayName: 'locate vsdevcmd via vswhere'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.13'
        addToPath: true

    - script: |
        call $(vsdevcmd) -arch=amd64
        set PYTHONPATH=
        set PYTHONHOME=
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel numpy
        python -m cibuildwheel --platform windows --archs AMD64 --output-dir $(REPOROOT)\out
      displayName: Build wheels

    #- task: SDLNativeRules@3
    #  inputs:
    #    msBuildArchitecture: amd64
    #    setupCommandlines: '"$(vscmake)" $(REPOROOT) -A x64 -B $(REPOROOT)\windows_out -DOCOS_BUILD_PYTHON=ON -DOCOS_ENABLE_CTEST=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo'
    #    msBuildCommandline: '"$(vsmsbuild)" "$(REPOROOT)\windows_out\onnxruntime_extensions.sln" /p:RunCodeAnalysis=true /p:platform=x64 /p:configuration=RelWithDebInfo /p:VisualStudioVersion="17.0" /m /p:PreferredToolArchitecture=x64 /t:extensions_shared;extensions_pydll'
    #    excludedPaths: '$(REPOROOT)\windows_out#$(Build.SourcesDirectory)\cmake#C:\program files (x86)'
    #  displayName: 'Run the PREfast SDL Native Rules for MSBuild'

    - task: PostAnalysis@2
      inputs:
        GdnBreakGdnToolSDLNativeRulesSeverity: Warning
        GdnBreakGdnToolSDLNativeRules: true
      displayName: 'Guardian Break'

    - script: |
        7z x $(REPOROOT)\out\*.whl -o$(REPOROOT)\out\*
      displayName: unzip the package

    - template: win-esrp-dll.yml
      parameters:
        FolderPath: '$(REPOROOT)\out'
        DisplayName: 'Sign runtime DLLs'
        Pattern: '*.pyd,*.dll'

    - script: |
        for /D %%i in ("out\onnxruntime_extensions*-win*") do (
          7z u %%i.whl .\%%i\*
          copy %%i\onnxruntime_extensions\*.pyd out\
          rmdir /s /q %%i
          )
        for %%i in (out\*.pyd) do (
          move %%i %%~pni.dll
          )
        dir out\*.*
      workingDirectory: '$(REPOROOT)'
      displayName: zip package

    - script: 'pip install twine==3.4.2'
      displayName: 'Install Twine'

    - task: TwineAuthenticate@1
      displayName: 'Twine Authenticate '
      inputs:
        artifactFeed: PublicPackages/${{ parameters.artifact_feed }}

    - script: 'python -m twine upload -r ${{ parameters.artifact_feed }} --config-file $(PYPIRC_PATH) --non-interactive --skip-existing *.whl'
      workingDirectory: '$(REPOROOT)\out'
      displayName: 'Uploading wheels to ${{ parameters.artifact_feed }}'
      retryCountOnTaskFailure: 3
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)