# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
###############################################################################
from typing import Callable


class PyCustomOpDef:
    undefined: int = ...
    dt_float: int = ...
    dt_uint8: int = ...
    dt_int8: int = ...
    dt_uint16: int = ...
    dt_int16: int = ...
    dt_int32: int = ...
    dt_int64: int = ...
    dt_string: int = ...
    dt_bool: int = ...
    dt_float16: int = ...
    dt_double: int = ...
    dt_uint32: int = ...
    dt_uint64: int = ...
    dt_complex64: int = ...
    dt_complex128: int = ...
    dt_bfloat16: int = ...

    def install_hooker(self, invocation_handler: Callable) -> None:
        ...
    ...


def enable_py_op(enabled: bool) -> bool:
    ...


def add_custom_op(opdef: PyCustomOpDef) -> None:
    ...


def hash_64(s: str, num_buckets: int, fast: int) -> int:
    ...


def default_opset_domain() -> str:
    ...
