/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo4j;

import ai.onnxruntime.*;
import ai.onnxruntime.extensions.OrtxPackage;

public class App {
    public String inference(){
        try {
            var env = OrtEnvironment.getEnvironment();
            var sess_opt = new OrtSession.SessionOptions();
            var pkg = new OrtxPackage();
            sess_opt.registerCustomOpLibrary(pkg.getLibraryPath());
            var session = env.createSession("model.onnx", sess_opt);

            sess_opt.close();
            pkg.close();
        } catch(OrtException e1) {
            return e1.getMessage();
        }

        return "OK.";
    }

    public static void main(String[] args) {
        System.out.println(new App().inference());
    }
}
