parameters:
- name: JavaPackagingandPublishing
  displayName: Package and Publish Java Package
  type: boolean
  default: true
stages:
- stage: Java_Packaging
  jobs:
  - job: Windows_CPU_Java_Packaging
    workspace:
      clean: all
    pool: {name: 'onnxruntime-Win-CPU-2022'}

    steps:
    - script: |
        sh ./build.sh -DOCOS_BUILD_JAVA=ON
      displayName: build the extensions java package

    - task: CopyFiles@2
      displayName: 'Copy Java Files for $(Agent.OS) Arch to Artifact Staging Directory'
      inputs:
        SourceFolder: 'out/$(Agent.OS)/RelWithDebInfo/java/build/libs'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - job: Linux_CPU_Java_Packaging
    workspace:
      clean: all
    pool: {name: 'Azure-Pipelines-EO-Ubuntu-2004-aiinfra'}

    steps:
    - script: |
        sh ./build.sh -DOCOS_BUILD_JAVA=ON
      displayName: build the extensions java package

    - task: CopyFiles@2
      displayName: 'Copy Java Files for $(Agent.OS) Arch to Artifact Staging Directory'
      inputs:
        SourceFolder: 'out/$(Agent.OS)/RelWithDebInfo/java/build/libs'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - job: MacOS_CPU_Java_Packaging
    workspace:
      clean: all
    pool:
      vmImage: 'macOS-13'

    steps:
    - script: |
        sh ./build.sh -DOCOS_BUILD_JAVA=ON
      displayName: build the extensions java package

    - task: CopyFiles@2
      displayName: 'Copy Java Files for $(Agent.OS) Arch to Artifact Staging Directory'
      inputs:
        SourceFolder: 'out/$(Agent.OS)/RelWithDebInfo/java/build/libs'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

- stage: Publish_Java_Package
  dependsOn: Java_Packaging
  jobs:
  - job: Publich_and_Cleanup
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'onnxruntime-extensions-java-cpu'

    - template: templates/component-governance-component-detection-steps.yml
      parameters :
        condition : 'succeeded'

    - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
      displayName: 'Clean Agent Directories'
      condition: always()
