parameters:
- name: DoCompliance
  displayName: Run Compliance Tasks?
  type: boolean
  default: true

- name: DoEsrp
  displayName: Run code sign tasks? Must be true if you are doing an OnnxRuntime extensions release.
  type: boolean
  default: true

- name: IsReleaseBuild
  displayName: Is this a release build? Set it to true if you are doing an OnnxRuntime extensions release.
  type: boolean
  default: false

- name: NugetVersionSuffix
  displayName: Update nuget version suffix (e.g. alpha/beta/rc, only if publishing to nuget.org, otherwise leave as "none").
  type: string
  default: none

trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "*"
      
stages:
- template: templates/build-package-for-nuget.yml
  parameters:
    DoCompliance: ${{ parameters.DoCompliance }}
    DoEsrp: ${{ parameters.DoEsrp }}
    IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
    NugetVersionSuffix: ${{ parameters.NugetVersionSuffix }}
    OrtNugetPackageId: 'Microsoft.ML.OnnxRuntime.Extensions'
