jobs:
- job: linux
  timeoutInMinutes: 120
  pool: {vmImage: 'ubuntu-latest', name: 'Linux-CPU'}
  variables:
    CIBW_BUILD: "cp3{7,8,9,10}-*"

  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
