parameters:
- name: BuildAzureOp
  displayName: 'Build and test AzureEP ops'
  type: string
  values:
  - '0'
  - '1'
  default: '0'

jobs:
- job: linux
  timeoutInMinutes: 180
  pool: {name: 'Azure-Pipelines-EO-Ubuntu-2004-aiinfra'}
  variables:
    CIBW_BUILD: "cp3{8,9,10,11}-*"
    CIBW_ENVIRONMENT: "OCOS_ENABLE_AZURE=${{ parameters.BuildAzureOp }}"

  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
